geo_app/urls.py
from django.urls import path 

from .views import HomeView 

urlpatterns = [
    path('', HomeView, name="home"),
] 

ip_geo/urls.py
from django.contrib import admin
from django.urls import path,include 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("geo_app.urls")),
]  

geo_app/models.py
from django.db import models

# Create your models here.

geo_app/forms.py
from django import forms



# ip address form 
class AddressForm(forms.Form):
    ip_address = forms.CharField(max_length=18, required=True)

    # clean ip_form 
    def clean_ip_address(self):
        ip_address = self.cleaned_data["ip_address"]

        # if not all(i.isdigit() for i in ip_address ):
        #     return forms.ValidationError("Ip address must be a number")
        if ip_address == " ":
            return forms.ValidationError("Ip cannot be empty")
        
        return ip_address

geo_app/views.py
from django.shortcuts import render
from django.contrib import messages 


from .forms import AddressForm

import requests  
import json  


# home view 
def HomeView(request):
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            ip = form.cleaned_data["ip_address"]
            try:
                url = 'http://ip-api.com/batch'
                address = [ip]
                res = requests.post(url, json=address)
                res_data = json.dumps(res.json())
                json_data = json.loads(res_data)


                query = json_data[0]["query"]
                country = json_data[0]["country"]
                country_code =json_data[0]["countryCode"]
                region = json_data[0]["region"]
                region_name = json_data[0]["regionName"]
                city = json_data[0]["city"]
                zip_code = json_data[0]["zip"]
                lat = json_data[0]["lat"]
                lon = json_data[0]["lon"]
                timezone = json_data[0]["timezone"]
                isp = json_data[0]["isp"]
                isp_org = json_data[0]["org"]
                isp_ass = json_data[0]["as"]
                


                data = {
                    "query":query,
                    "country":country,
                    "country_code":country_code,
                    "region":region,
                    "region_name":region_name,
                    "city":city,
                    "zip_code":zip_code,
                    "lat":lat,
                    "lon":lon,
                    "timezone":timezone,
                    "isp":isp,
                    "isp_org":isp_org,
                    "isp_ass":isp_ass
                }
                return render(request, "home.html", {"data":data, "form":form})
            
            except:
                messages.error(request, "unable to get IP info")

            # return render(request, "home.html", data)
            
        else:
            messages.error(request, "Please provide a valid input")
    else:
        form = AddressForm()
    return render(request, "home.html", {"form":form})
        

geo_app/templates/home.html
{% block content %} 
{% load static %} 
<html>
    <head>
        <title>Ip extract</title>
        <link href="{% static 'css/home.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2><i>IP Extract</i></h2>
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <input class="ip" type="text" name="ip_address" maxlength="18" required id="id_ip_address" placeholder="Enter IP Address">
                <br/><input class="submit" type="submit" value="search">
            </form>
            <div class="result">
                <p><b>IP</b>: {{data.query}}</p>
                <p><b>Country</b>: {{data.country}}</p>
                <p><b>Country Code</b>: {{data.country_code}}</p>
                <p><b>Region</b>: {{data.region}}</p>
                <p><b>Region Name</b>: {{data.region_name}}</p>
                <p><b>City</b>: {{data.city}}</p>
                <p><b>Zip</b>: {{data.zip_code}}</p>
                <p><b>Latitude</b>: {{data.lat}}</p>
                <p><b>Longitude</b>: {{data.lon}}</p>
                <p><b>Timezone</b>: {{data.timezone}}</p>
                <p><b>ISP</b>: {{data.isp}}</p>
                <p><b>ISP Organization</b>: {{data.isp_org}}</p>
                <p><b>ISP Association</b>: {{data.isp_ass}}</p>

            </div>
            
        </div>
    </body>

</html>
{% endblock %}